# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fulcrum
email: fulcrum-info@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Fulcrum is a publishing platform that helps publishers present the
  full richness of their authors' research outputs in a durable, discoverable,
  and flexible form.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fulcrum.org" # the base hostname & protocol for your site
#twitter_username:
#github_username:  mlibrary/fulcrum
github_username: curationexperts/heliotrope
# Build settings
markdown: kramdown
host: fulcrum.org
